### ISSUE TITLE
建议去官方CTFd库去Fork一个然后提交一个requests

### ISSUE THREAD

**Issue by eonun** [Gu-f/CTFd_chinese_CN#1]
建议去官方CTFd库去Fork一个然后将主题文件放上去，再提交一个requests，让官方使用本库中的中文主题，这样你相当于对CTFd这样的大项目有了贡献，可以成为你的简历的，同时也方便我们国内的使用

**Comment by Gu-f** [comment]
感谢你的建议！我会考虑的，主题目前仅用户使用为中文，其中管理模式有一部分因影响不大未完成汉化，暂时并不健全。
