### ISSUE TITLE
为什么他的网页内容不能修改成中文

### ISSUE THREAD

**Issue by mcyydscc** [Gu-f/CTFd_chinese_CN#4]
为什么他的网页内容不能修改成中文，一修改就会500报错，而且不能上传logo什么的，也会500报错

**Comment by Gu-f** [comment]
你是在哪个位置修改的。上传logo出现500报错，通常是服务端造成的，请检查下是不是版本混用了，部分版本汉化混用可以，有些不行，最好是一一对应。

**Comment by mcyydscc** [comment]
> 你是在哪个位置修改的。上传logo出现500个报错，通常是服务端造成的，请检查下是不是版本混用了，部分版本汉化混用了，可能不是，最好是一。

我用WinSCP连接服务器，然后在theme，模板里面修改html的，然后如果在网站后台上传logo，那个配置界面也会500报错

**Comment by Gu-f** [comment]
直接在模板里面修改html如果标签没有闭合错误的化是没问题的。服务端报500错误你看下后台具体是报什么错呢？

**Comment by mcyydscc** [comment]
> 直接在模板里面修改html如果标签没有闭合错误的化是没问题的。服务端报500错误你看下后台具体是报什么错呢？
![1](https://user-images.githubusercontent.com/90653809/147384204-c599e046-15be-4d45-9831-a74617534d92.png)
就像这样

**Comment by Gu-f** [comment]
500通常是服务端错误，请截图或复制下响应日志报的错误信息看下。前台debug模式启动能看到日志，或后台debug模式启动你日志导出的位置在哪，就看那个日志。

**Comment by mcyydscc** [comment]
![6](https://user-images.githubusercontent.com/90653809/147384356-68187529-c8a6-4705-bf91-98bab1a6d23c.png)
麻烦了大佬

**Comment by mcyydscc** [comment]
> 500通常是服务端错误，请截图或复制下响应日志报的错误信息看下。前台debug模式启动能看到日志，或后台debug模式启动你日志导出的位置在哪，就看那个日志。
![6](https://user-images.githubusercontent.com/90653809/147384370-aec7eacc-0caa-48e5-a1c1-68d8899f879e.png)

麻烦了大佬

**Comment by Gu-f** [comment]
CTFd的响应日志,是web服务的日志，不是系统messages日志,,,,,,,,,,,,,

**Comment by Gu-f** [comment]
如果您对web这块相关后台逻辑不太熟悉的话，建议您重新进行一下templates模板的中英文修改。先保证能正常不出现500的错误，然后修改一个文件完成后，启动一下服务，确认一下是否正常。确保修改的每个文件都能正常运行，不出现异常。

**Comment by Gu-f** [comment]
这样可以更好的定位您修改的问题和错误的位置。

**Comment by mcyydscc** [comment]
> 这样可以更好的定位您修改的问题和错误的位置。
好的好的，非常感谢您
