### ISSUE TITLE
大佬能否告诉一下，CTFd3.4.0的导航栏汉化要在哪里修改

### ISSUE THREAD

**Issue by mcyydscc** [Gu-f/CTFd_chinese_CN#5]
大佬您好，非常感谢您的CTFd的汉化
其次，因为3.1.0汉化包在我的3.4.0上不兼容，登陆后会出现权限不足的问题，您能否告诉我一下她的导航栏汉化要在哪里修改

**Comment by Gu-f** [comment]
`<ProjectRoot>/CTFd/themes/admin/templates/base.html`  普通用户
`<ProjectRoot>/CTFd/themes/core/templates/components/navbar.html`   后台

**Comment by Gu-f** [comment]
如果3.4.0 submissions 页面不显示 user challenge，请参考该issue的解决方法。
#3

**Comment by mcyydscc** [comment]
> 如果3.4.0 submissions 页面不显示 user challenge，请参考该issue的解决方法。 #3

大佬，我昨晚汉化了一下3.4.0的，除了几个找不到的页面，其他基本汉化完成了，您需要吗，我发给你

**Comment by Gu-f** [comment]
如果可以的话欢迎按照仓库文件目录提交格式拉取一个request，非常期待您的贡献。

**Comment by mcyydscc** [comment]
> 如果可以的话欢迎按照仓库文件目录提交格式拉取一个request，非常期待您的贡献。

你好，我目前已经基本汉化完毕了，除了使用vue的页面，因为我对这块不太熟悉，能否加个联系方式，我发给你，因为我对github的request的机制不太熟悉

**Comment by Gu-f** [comment]
可以将代码打包发送到邮箱：x2417225563@163.com，您看到这条信息后回复下，为避免垃圾邮件，我将在您看到后删除该comment。

**Comment by mcyydscc** [comment]
> 可以将代码打包发送到邮箱：[x2417225563@163.com](mailto:x2417225563@163.com)，您看到这条信息后回复下，为避免垃圾邮件，我将在您看到后删除该comment。

好的收到

**Comment by Gu-f** [comment]
已收到

**Comment by Gu-f** [comment]
感谢您的贡献。已更新V3.4.0汉化版本，在您的基础上做了title的脱敏和CDN的修改(优化大陆访问速度解决由此导致的卡顿问题)。

目前已合并到仓库，如果没有其他问题，此issue已完成，我将关闭该issue。
