### ISSUE TITLE
请问 覆盖了官方的代码后再执行sudo docker-compose up 页面没有更新是什么情况 我是小白

### ISSUE THREAD

**Issue by ZH-UCAS** [Gu-f/CTFd_chinese_CN#8]
请问 覆盖了官方的代码后再执行sudo docker-compose up 页面没有更新是什么情况 我是小白

**Comment by ZH-UCAS** [comment]
![image](https://user-images.githubusercontent.com/23288916/156340647-65086847-6bb7-4c78-9b5f-3e5d01a9b637.png)

**Comment by Gu-f** [comment]
如果您之前用docker-compose up启动过了，再次使用他启动的时候，本地修改的代码很可能您忘记同步到docker容器中。
请覆盖后尝试使用docker-compose build重新构建
或尝试使用sudo docker-compose up --build启动

**Comment by ZH-UCAS** [comment]
非常感谢 已经成功汉化
